# Generated by Django 3.1.1 on 2020-09-26 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
    ]
