# Generated by Django 3.1.1 on 2020-09-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200928_1213'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('article_id',), name='unique_article_id'),
        ),
    ]
