# Generated by Django 3.1.1 on 2020-10-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201001_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='namespace',
            field=models.CharField(default='public', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
