# Generated by Django 3.1.1 on 2020-10-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201001_2003'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='article',
            name='unique_article_id',
        ),
        migrations.RemoveConstraint(
            model_name='article',
            name='unique_title',
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('namespace', 'article_id'), name='unique_article_id'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('namespace', 'title'), name='unique_title'),
        ),
    ]
